FROM golang:1.21-alpine

RUN apk add --no-cache git bash ca-certificates

WORKDIR /app

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

COPY migrations ./migrations

ENTRYPOINT ["bash"]
